### ISSUE TITLE
Compile for Arm64

### ISSUE THREAD

**Issue by coreybruce** [farisawan-2000/kirby64#52]
Hey there I wish to compile for Arm64, I am using Manjar oARm64 on my raspberry pi but I think this needs to be fixed to support Arm64.

First I had to remove the -m32 argument from gcc on both the main make file and the libreultra file but than I run into this issue while compiling.

```

[corey@manjaro-pi kirby64]$ make setup
make -C libreultra -j4
make[1]: Entering directory '/home/corey/Stuff/projects/kirby64/libreultra'
tools/ido-5.3recomp/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -fullwarn -O3 -nostdinc -I include/2.0I -I include/2.0I/PR -DTARGET_N64 -D_FINALROM -DF3DEX_GBI -DNDEBUG -I include/2.0I -I include/2.0I/PR -I src/  -mips2 -32 -o build/2.0I/src/audio/cents2ratio.o src/audio/cents2ratio.c
tools/ido-5.3recomp/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -fullwarn -O3 -nostdinc -I include/2.0I -I include/2.0I/PR -DTARGET_N64 -D_FINALROM -DF3DEX_GBI -DNDEBUG -I include/2.0I -I include/2.0I/PR -I src/  -mips2 -32 -o build/2.0I/src/audio/auxbus.o src/audio/auxbus.c
tools/ido-5.3recomp/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -fullwarn -O3 -nostdinc -I include/2.0I -I include/2.0I/PR -DTARGET_N64 -D_FINALROM -DF3DEX_GBI -DNDEBUG -I include/2.0I -I include/2.0I/PR -I src/  -mips2 -32 -o build/2.0I/src/audio/bnkf.o src/audio/bnkf.c
tools/ido-5.3recomp/ido5.3_recomp/cc: tools/ido-5.3recomp/ido5.3_recomp/cc: cannot execute binary file
tools/ido-5.3recomp/ido5.3_recomp/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -fullwarn -O3 -nostdinc -I include/2.0I -I include/2.0I/PR -DTARGET_N64 -D_FINALROM -DF3DEX_GBI -DNDEBUG -I include/2.0I -I include/2.0I/PR -I src/  -mips2 -32 -o build/2.0I/src/audio/copy.o src/audio/copy.c
tools/ido-5.3recomp/ido5.3_recomp/cc: tools/ido-5.3recomp/ido5.3_recomp/cc: cannot execute binary file
make[1]: *** [Makefile:186: build/2.0I/src/audio/cents2ratio.o] Error 126
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:186: build/2.0I/src/audio/auxbus.o] Error 126
tools/ido-5.3recomp/ido5.3_recomp/cc: tools/ido-5.3recomp/ido5.3_recomp/cc: cannot execute binary file
make[1]: *** [Makefile:186: build/2.0I/src/audio/bnkf.o] Error 126
tools/ido-5.3recomp/ido5.3_recomp/cc: tools/ido-5.3recomp/ido5.3_recomp/cc: cannot execute binary file
make[1]: *** [Makefile:186: build/2.0I/src/audio/copy.o] Error 126
make[1]: Leaving directory '/home/corey/Stuff/projects/kirby64/libreultra'
make: *** [Makefile:272: setup] Error 2
```

**Comment by farisawan-2000** [comment]
Hi, thanks for bringing this to my attention!

Basically, the repo is using a static recompilation of the original game's compiler, in order to speed up build times (which is necessary for a repo of this size; it almost halves the build time!).

The thing is, instead of including the source and tools to build the recompilation of the compiler, I've simply included the binaries. This was a good step in my opinion because it cut down on the long time to build the compiler itself (which would have to be done twice, since the libreultra submodule also has a copy of the recomp).

There are two ways to go about this: Either I could tell you to build [qemu-irix](https://github.com/n64decomp/qemu-irix/), or I could go in and put in the recomp sources and build system. I'd be glad to do the latter, but I'm currently swamped with another feature at the moment.

So for now, try building qemu and setting `CC` in the Makefile (line 30) to the qemu-irix version.

(Also, I saw your issue in the mk64 repository, and I should clarify that besides sm64, none of these decomps produce native executables; only the exact N64 ROM until the game is 100% complete and somebody goes through the effort to write the necessary PC interfacing code.)

**Comment by coreybruce** [comment]
Hmm well I have qemu-irix installed and ahh I see well it's ok if it takes some time to re code I can understand that.

Oh really it doesn't compile a native binary until it's 100% complete? hmm ok I understand, anything else I can do to help?
